name: "Setup Build Environment"
description: "Install dependencies and LLVM/Clang for Persephone. Drogon is fetched and statically linked via CMake FetchContent."

inputs:
  install-lcov:
    description: "Whether to install lcov for coverage"
    required: false
    default: "false"
  install-rpm:
    description: "Whether to install rpm for packaging"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install LLVM/Clang
      shell: bash
      run: |
        sudo ${{ github.workspace }}/.github/llvm.sh 21 all
        # Ensure llvm tools are in PATH
        echo "/usr/lib/llvm-21/bin" >> $GITHUB_PATH
        # Create symlinks for llvm tools without version suffix
        sudo ln -sf /usr/bin/llvm-cov-21 /usr/bin/llvm-cov
        sudo ln -sf /usr/bin/llvm-profdata-21 /usr/bin/llvm-profdata

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        PACKAGES=(
          ninja-build
          nlohmann-json3-dev
          libpq-dev
          libsodium-dev
          libjsoncpp-dev
          uuid-dev
          zlib1g-dev
          openssl
          libssl-dev
          cmake
          libyaml-cpp-dev
          libldns-dev
          libstdc++-11-dev
          libevent-dev
          libicu-dev
        )
        if [[ "${{ inputs.install-lcov }}" == "true" ]]; then
          PACKAGES+=(lcov)
        fi
        if [[ "${{ inputs.install-rpm }}" == "true" ]]; then
          PACKAGES+=(rpm)
        fi
        sudo apt-get install -y "${PACKAGES[@]}"
        # jsoncpp is a bit weird on ubuntu vs fedora
        sudo ln -sf /usr/include/jsoncpp/json/ /usr/include/json
