name: "Docker"

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - run: ./scripts/build_docker.sh